# Copyright 2019 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Download Kubernetes binaries
  unarchive:
    src: "{{ kubernetes_http_source }}/{{ kubernetes_semver }}-azs/binaries/kubernetes-node-linux-{{ kubernetes_goarch }}.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Copy Kubernetes binaries
  copy:
    src: /tmp/kubernetes/node/bin/{{ item }}
    dest: "/usr/bin/{{ item }}"
    mode: 0755
    owner: root
    group: root
  loop: "{{ kubernetes_bins }}"

- name: Download Kubernetes images
  get_url:
    url: "{{ kubernetes_http_source }}/v{{ kubernetes_semver }}-azs/images/linux/{{ kubernetes_goarch }}/{{ item }}"
    # TODO(akutz) Write a script to separately download the checksum
    #             and verify the associated file using the correct
    #             checksum file format
    #checksum: "sha1:{{ kubernetes_http_source }}/bin/linux/amd64/{{ item }}.sha1"
    dest: "/tmp/{{ item }}"
  loop: "{{ kubernetes_imgs }}"

- name: Load Kubernetes images
  shell: 'CONTAINERD_NAMESPACE="k8s.io" ctr images import /tmp/{{ item }}'
  loop: "{{ kubernetes_imgs }}"

- name: Remove Kubernetes images
  file:
    state: absent
    path: "/tmp/{{ item }}"
  loop: "{{ kubernetes_imgs }}"
